import { 
  Department, 
  Domain, 
  EmployeeDirectoryItem, 
  ProjectItem, 
  RecognitionItem, 
  AnnouncementItem,
  SalaryRecord,
  MedicalRecord,
  AttendanceRecord,
  LeaveRecord,
  ActivityLogItem,
  MarketplaceProduct,
  DemoOrder,
  AppointmentSlot,
  NotificationItem
} from '../types';

export const DEPARTMENTS_DATA: Department[] = [
  { id: 'DEP-ENG', name: 'Engineering', code: 'ENG', head: 'Vikram Malhotra', description: 'Core software engineering, platform architecture, and development operations.', status: 'ACTIVE' },
  { id: 'DEP-AI', name: 'AI Research', code: 'AI', head: 'Dr. Radhika Sen', description: 'Machine learning research, generative AI pipelines, and agentic workflows.', status: 'ACTIVE' },
  { id: 'DEP-HR', name: 'Human Resources', code: 'HR', head: 'Ananya Sharma', description: 'Talent acquisition, employee wellness, cultural development, and operations.', status: 'ACTIVE' },
  { id: 'DEP-FIN', name: 'Finance', code: 'FIN', head: 'Karthik Raman', description: 'Financial planning, accounting, fiscal governance, and reporting.', status: 'ACTIVE' },
  { id: 'DEP-PROD', name: 'Product', code: 'PROD', head: 'Tanvi Deshmukh', description: 'Product strategy, roadmap execution, user feedback, and metric evaluation.', status: 'ACTIVE' },
  { id: 'DEP-OPS', name: 'Operations', code: 'OPS', head: 'Manish Verma', description: 'Infrastructure logistics, facilities, security compliance, and vendor management.', status: 'ACTIVE' },
  { id: 'DEP-MKT', name: 'Marketing', code: 'MKT', head: 'Pooja Nair', description: 'Brand expansion, corporate communications, events, and inbound demand generation.', status: 'ACTIVE' },
  { id: 'DEP-DES', name: 'Design', code: 'DES', head: 'Arjun Mehta', description: 'Design systems, product UI/UX research, and editorial visual craft.', status: 'ACTIVE' },
];

export const DOMAINS_DATA: Domain[] = [
  { id: 'DOM-AI', name: 'AI & Data Science', code: 'AI-DS', description: 'Deep learning, predictive analytics, LLMs, and data intelligence.', status: 'ACTIVE' },
  { id: 'DOM-SWE', name: 'Software Engineering', code: 'SWE', description: 'Full-stack application development, API microservices, and system programming.', status: 'ACTIVE' },
  { id: 'DOM-CLD', name: 'Cloud & DevOps', code: 'CLD', description: 'Kubernetes orchestration, CI/CD automation, and cloud architecture.', status: 'ACTIVE' },
  { id: 'DOM-QA', name: 'Testing & QA', code: 'QA', description: 'Automated test pipelines, load testing, performance profiling, and QA.', status: 'ACTIVE' },
  { id: 'DOM-SEC', name: 'Cyber Security', code: 'SEC', description: 'Threat modeling, zero-trust protocols, identity management, and compliance.', status: 'ACTIVE' },
  { id: 'DOM-HR', name: 'HR Operations', code: 'HRO', description: 'Talent management, people analytics, policy, and learning & development.', status: 'ACTIVE' },
  { id: 'DOM-FIN', name: 'Finance & Accounts', code: 'FA', description: 'Treasury, payroll processing, tax compliance, and auditing.', status: 'ACTIVE' },
  { id: 'DOM-MKT', name: 'Growth & Marketing', code: 'GM', description: 'Enterprise product positioning, digital growth campaigns, and PR.', status: 'ACTIVE' },
  { id: 'DOM-UX', name: 'UI/UX Design', code: 'UXD', description: 'Interface architecture, design token systems, accessibility, and user research.', status: 'ACTIVE' },
];

export const EMPLOYEES_DATA: EmployeeDirectoryItem[] = [
  {
    employeeId: 'PRX-001',
    name: 'Siddharth Rao',
    email: 'admin@prionix-demo.com',
    departmentId: 'DEP-ENG',
    departmentName: 'Engineering',
    domainId: 'DOM-SWE',
    domainName: 'Software Engineering',
    designation: 'VP of Engineering',
    status: 'ACTIVE',
    joiningDate: '2022-03-15',
    manager: 'CEO Office',
    location: 'Bangalore Campus, BLR-01',
    phone: '+91 98450 11001',
    avatarUrl: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80',
  },
  {
    employeeId: 'PRX-002',
    name: 'Devika Krishnan',
    email: 'employee@prionix-demo.com',
    departmentId: 'DEP-AI',
    departmentName: 'AI Research',
    domainId: 'DOM-AI',
    domainName: 'AI & Data Science',
    designation: 'Senior AI Research Engineer',
    status: 'ACTIVE',
    joiningDate: '2023-01-10',
    manager: 'Dr. Radhika Sen',
    location: 'Bangalore Campus, BLR-02',
    phone: '+91 98450 11002',
    avatarUrl: 'https://images.unsplash.com/photo-1580489944761-15a19d654956?w=150&auto=format&fit=crop&q=80',
  },
  {
    employeeId: 'PRX-003',
    name: 'Dr. Radhika Sen',
    email: 'radhika.sen@prionix-corp.demo',
    departmentId: 'DEP-AI',
    departmentName: 'AI Research',
    domainId: 'DOM-AI',
    domainName: 'AI & Data Science',
    designation: 'Head of AI Research',
    status: 'ACTIVE',
    joiningDate: '2021-08-01',
    manager: 'CEO Office',
    location: 'Bangalore Campus, BLR-02',
    phone: '+91 98450 11003',
    avatarUrl: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=150&auto=format&fit=crop&q=80',
  },
  {
    employeeId: 'PRX-004',
    name: 'Vikram Malhotra',
    email: 'vikram.malhotra@prionix-corp.demo',
    departmentId: 'DEP-ENG',
    departmentName: 'Engineering',
    domainId: 'DOM-SWE',
    domainName: 'Software Engineering',
    designation: 'Principal Architect',
    status: 'ACTIVE',
    joiningDate: '2021-04-12',
    manager: 'Siddharth Rao',
    location: 'Hyderabad Tech Park',
    phone: '+91 98450 11004',
  },
  {
    employeeId: 'PRX-005',
    name: 'Ananya Sharma',
    email: 'ananya.sharma@prionix-corp.demo',
    departmentId: 'DEP-HR',
    departmentName: 'Human Resources',
    domainId: 'DOM-HR',
    domainName: 'HR Operations',
    designation: 'Chief People Officer',
    status: 'ACTIVE',
    joiningDate: '2022-01-05',
    manager: 'CEO Office',
    location: 'Mumbai Corporate Office',
    phone: '+91 98450 11005',
  },
  {
    employeeId: 'PRX-006',
    name: 'Arjun Mehta',
    email: 'arjun.mehta@prionix-corp.demo',
    departmentId: 'DEP-DES',
    departmentName: 'Design',
    domainId: 'DOM-UX',
    domainName: 'UI/UX Design',
    designation: 'Design Director',
    status: 'ACTIVE',
    joiningDate: '2022-06-18',
    manager: 'Tanvi Deshmukh',
    location: 'Bangalore Campus, BLR-01',
    phone: '+91 98450 11006',
  },
  {
    employeeId: 'PRX-007',
    name: 'Karthik Raman',
    email: 'karthik.raman@prionix-corp.demo',
    departmentId: 'DEP-FIN',
    departmentName: 'Finance',
    domainId: 'DOM-FIN',
    domainName: 'Finance & Accounts',
    designation: 'Director of Financial Operations',
    status: 'ACTIVE',
    joiningDate: '2021-11-20',
    manager: 'CEO Office',
    location: 'Mumbai Corporate Office',
    phone: '+91 98450 11007',
  },
  {
    employeeId: 'PRX-008',
    name: 'Tanvi Deshmukh',
    email: 'tanvi.deshmukh@prionix-corp.demo',
    departmentId: 'DEP-PROD',
    departmentName: 'Product',
    domainId: 'DOM-SWE',
    domainName: 'Software Engineering',
    designation: 'VP of Product Management',
    status: 'ACTIVE',
    joiningDate: '2022-05-14',
    manager: 'CEO Office',
    location: 'Bangalore Campus, BLR-01',
    phone: '+91 98450 11008',
  },
  {
    employeeId: 'PRX-009',
    name: 'Manish Verma',
    email: 'manish.verma@prionix-corp.demo',
    departmentId: 'DEP-OPS',
    departmentName: 'Operations',
    domainId: 'DOM-CLD',
    domainName: 'Cloud & DevOps',
    designation: 'Head of Cloud Infrastructure',
    status: 'ACTIVE',
    joiningDate: '2022-09-01',
    manager: 'Siddharth Rao',
    location: 'Pune Innovation Center',
    phone: '+91 98450 11009',
  },
  {
    employeeId: 'PRX-010',
    name: 'Pooja Nair',
    email: 'pooja.nair@prionix-corp.demo',
    departmentId: 'DEP-MKT',
    departmentName: 'Marketing',
    domainId: 'DOM-MKT',
    domainName: 'Growth & Marketing',
    designation: 'Head of Enterprise Marketing',
    status: 'ACTIVE',
    joiningDate: '2023-03-01',
    manager: 'CEO Office',
    location: 'Delhi Regional Office',
    phone: '+91 98450 11010',
  },
  {
    employeeId: 'PRX-011',
    name: 'Aakash Singhania',
    email: 'aakash.singhania@prionix-corp.demo',
    departmentId: 'DEP-ENG',
    departmentName: 'Engineering',
    domainId: 'DOM-CLD',
    domainName: 'Cloud & DevOps',
    designation: 'Lead DevOps & SRE Engineer',
    status: 'ACTIVE',
    joiningDate: '2023-04-15',
    manager: 'Manish Verma',
    location: 'Bangalore Campus, BLR-01',
    phone: '+91 98450 11011',
  },
  {
    employeeId: 'PRX-012',
    name: 'Bhavna Kulkarni',
    email: 'bhavna.kulkarni@prionix-corp.demo',
    departmentId: 'DEP-AI',
    departmentName: 'AI Research',
    domainId: 'DOM-AI',
    domainName: 'AI & Data Science',
    designation: 'Senior Machine Learning Specialist',
    status: 'ACTIVE',
    joiningDate: '2023-07-01',
    manager: 'Dr. Radhika Sen',
    location: 'Bangalore Campus, BLR-02',
    phone: '+91 98450 11012',
  },
  {
    employeeId: 'PRX-013',
    name: 'Chetan Bansal',
    email: 'chetan.bansal@prionix-corp.demo',
    departmentId: 'DEP-ENG',
    departmentName: 'Engineering',
    domainId: 'DOM-SEC',
    domainName: 'Cyber Security',
    designation: 'Lead InfoSec & Threat Auditor',
    status: 'ACTIVE',
    joiningDate: '2022-10-10',
    manager: 'Vikram Malhotra',
    location: 'Hyderabad Tech Park',
    phone: '+91 98450 11013',
  },
  {
    employeeId: 'PRX-014',
    name: 'Deepika Joshi',
    email: 'deepika.joshi@prionix-corp.demo',
    departmentId: 'DEP-ENG',
    departmentName: 'Engineering',
    domainId: 'DOM-QA',
    domainName: 'Testing & QA',
    designation: 'Lead Quality Assurance Architect',
    status: 'ACTIVE',
    joiningDate: '2023-02-12',
    manager: 'Vikram Malhotra',
    location: 'Pune Innovation Center',
    phone: '+91 98450 11014',
  },
  {
    employeeId: 'PRX-015',
    name: 'Eshaan Nambiar',
    email: 'eshaan.nambiar@prionix-corp.demo',
    departmentId: 'DEP-DES',
    departmentName: 'Design',
    domainId: 'DOM-UX',
    domainName: 'UI/UX Design',
    designation: 'Senior Product Designer',
    status: 'ACTIVE',
    joiningDate: '2023-05-18',
    manager: 'Arjun Mehta',
    location: 'Bangalore Campus, BLR-01',
    phone: '+91 98450 11015',
  },
  {
    employeeId: 'PRX-016',
    name: 'Fatima Zaidi',
    email: 'fatima.zaidi@prionix-corp.demo',
    departmentId: 'DEP-HR',
    departmentName: 'Human Resources',
    domainId: 'DOM-HR',
    domainName: 'HR Operations',
    designation: 'HR Business Partner',
    status: 'ACTIVE',
    joiningDate: '2023-08-01',
    manager: 'Ananya Sharma',
    location: 'Mumbai Corporate Office',
    phone: '+91 98450 11016',
  },
  {
    employeeId: 'PRX-017',
    name: 'Gaurav Tewari',
    email: 'gaurav.tewari@prionix-corp.demo',
    departmentId: 'DEP-FIN',
    departmentName: 'Finance',
    domainId: 'DOM-FIN',
    domainName: 'Finance & Accounts',
    designation: 'Senior Financial Analyst',
    status: 'ACTIVE',
    joiningDate: '2023-09-15',
    manager: 'Karthik Raman',
    location: 'Mumbai Corporate Office',
    phone: '+91 98450 11017',
  },
  {
    employeeId: 'PRX-018',
    name: 'Harini Sundaram',
    email: 'harini.sundaram@prionix-corp.demo',
    departmentId: 'DEP-PROD',
    departmentName: 'Product',
    domainId: 'DOM-SWE',
    domainName: 'Software Engineering',
    designation: 'Senior Technical Product Manager',
    status: 'ACTIVE',
    joiningDate: '2023-06-01',
    manager: 'Tanvi Deshmukh',
    location: 'Bangalore Campus, BLR-01',
    phone: '+91 98450 11018',
  },
  {
    employeeId: 'PRX-019',
    name: 'Ishaan Chopra',
    email: 'ishaan.chopra@prionix-corp.demo',
    departmentId: 'DEP-ENG',
    departmentName: 'Engineering',
    domainId: 'DOM-SWE',
    domainName: 'Software Engineering',
    designation: 'Senior Backend Developer (Go/Node)',
    status: 'ACTIVE',
    joiningDate: '2023-11-01',
    manager: 'Vikram Malhotra',
    location: 'Hyderabad Tech Park',
    phone: '+91 98450 11019',
  },
  {
    employeeId: 'PRX-020',
    name: 'Jasleen Kaur',
    email: 'jasleen.kaur@prionix-corp.demo',
    departmentId: 'DEP-MKT',
    departmentName: 'Marketing',
    domainId: 'DOM-MKT',
    domainName: 'Growth & Marketing',
    designation: 'Digital Content & Brand Strategist',
    status: 'ACTIVE',
    joiningDate: '2024-01-15',
    manager: 'Pooja Nair',
    location: 'Delhi Regional Office',
    phone: '+91 98450 11020',
  },
  {
    employeeId: 'PRX-021',
    name: 'Kunal Saxena',
    email: 'kunal.saxena@prionix-corp.demo',
    departmentId: 'DEP-ENG',
    departmentName: 'Engineering',
    domainId: 'DOM-SWE',
    domainName: 'Software Engineering',
    designation: 'Frontend Lead (React/TypeScript)',
    status: 'ACTIVE',
    joiningDate: '2023-03-20',
    manager: 'Vikram Malhotra',
    location: 'Bangalore Campus, BLR-01',
    phone: '+91 98450 11021',
  },
  {
    employeeId: 'PRX-022',
    name: 'Lavanya Reddy',
    email: 'lavanya.reddy@prionix-corp.demo',
    departmentId: 'DEP-AI',
    departmentName: 'AI Research',
    domainId: 'DOM-AI',
    domainName: 'AI & Data Science',
    designation: 'NLP & LLM Systems Engineer',
    status: 'ACTIVE',
    joiningDate: '2024-02-01',
    manager: 'Devika Krishnan',
    location: 'Bangalore Campus, BLR-02',
    phone: '+91 98450 11022',
  },
  {
    employeeId: 'PRX-023',
    name: 'Mayank Aggarwal',
    email: 'mayank.aggarwal@prionix-corp.demo',
    departmentId: 'DEP-OPS',
    departmentName: 'Operations',
    domainId: 'DOM-CLD',
    domainName: 'Cloud & DevOps',
    designation: 'Kubernetes Platform Specialist',
    status: 'ACTIVE',
    joiningDate: '2024-03-10',
    manager: 'Aakash Singhania',
    location: 'Pune Innovation Center',
    phone: '+91 98450 11023',
  },
  {
    employeeId: 'PRX-024',
    name: 'Nandini Bhatt',
    email: 'nandini.bhatt@prionix-corp.demo',
    departmentId: 'DEP-ENG',
    departmentName: 'Engineering',
    domainId: 'DOM-QA',
    domainName: 'Testing & QA',
    designation: 'SDET Automation Engineer',
    status: 'ACTIVE',
    joiningDate: '2024-04-05',
    manager: 'Deepika Joshi',
    location: 'Pune Innovation Center',
    phone: '+91 98450 11024',
  },
  {
    employeeId: 'PRX-025',
    name: 'Omkar Gokhale',
    email: 'omkar.gokhale@prionix-corp.demo',
    departmentId: 'DEP-ENG',
    departmentName: 'Engineering',
    domainId: 'DOM-SEC',
    domainName: 'Cyber Security',
    designation: 'Security Operations Analyst',
    status: 'ACTIVE',
    joiningDate: '2024-05-15',
    manager: 'Chetan Bansal',
    location: 'Hyderabad Tech Park',
    phone: '+91 98450 11025',
  },
  {
    employeeId: 'PRX-026',
    name: 'Pratima Iyer',
    email: 'pratima.iyer@prionix-corp.demo',
    departmentId: 'DEP-HR',
    departmentName: 'Human Resources',
    domainId: 'DOM-HR',
    domainName: 'HR Operations',
    designation: 'Talent Acquisition Specialist',
    status: 'ACTIVE',
    joiningDate: '2024-06-01',
    manager: 'Fatima Zaidi',
    location: 'Mumbai Corporate Office',
    phone: '+91 98450 11026',
  },
  {
    employeeId: 'PRX-027',
    name: 'Raghav Chadha',
    email: 'raghav.chadha@prionix-corp.demo',
    departmentId: 'DEP-FIN',
    departmentName: 'Finance',
    domainId: 'DOM-FIN',
    domainName: 'Finance & Accounts',
    designation: 'Tax & Compliance Auditor',
    status: 'ACTIVE',
    joiningDate: '2023-12-01',
    manager: 'Gaurav Tewari',
    location: 'Mumbai Corporate Office',
    phone: '+91 98450 11027',
  },
  {
    employeeId: 'PRX-028',
    name: 'Sneha Murthy',
    email: 'sneha.murthy@prionix-corp.demo',
    departmentId: 'DEP-DES',
    departmentName: 'Design',
    domainId: 'DOM-UX',
    domainName: 'UI/UX Design',
    designation: 'Design Systems Architect',
    status: 'ACTIVE',
    joiningDate: '2024-01-08',
    manager: 'Arjun Mehta',
    location: 'Bangalore Campus, BLR-01',
    phone: '+91 98450 11028',
  },
  {
    employeeId: 'PRX-029',
    name: 'Tarun Varma',
    email: 'tarun.varma@prionix-corp.demo',
    departmentId: 'DEP-ENG',
    departmentName: 'Engineering',
    domainId: 'DOM-SWE',
    domainName: 'Software Engineering',
    designation: 'Full Stack Engineer',
    status: 'ACTIVE',
    joiningDate: '2024-07-15',
    manager: 'Kunal Saxena',
    location: 'Bangalore Campus, BLR-01',
    phone: '+91 98450 11029',
  },
  {
    employeeId: 'PRX-030',
    name: 'Urvashi Sen',
    email: 'urvashi.sen@prionix-corp.demo',
    departmentId: 'DEP-AI',
    departmentName: 'AI Research',
    domainId: 'DOM-AI',
    domainName: 'AI & Data Science',
    designation: 'Computer Vision Scientist',
    status: 'ON_LEAVE',
    joiningDate: '2023-10-15',
    manager: 'Devika Krishnan',
    location: 'Bangalore Campus, BLR-02',
    phone: '+91 98450 11030',
  },
  {
    employeeId: 'PRX-031',
    name: 'Varun Pillai',
    email: 'varun.pillai@prionix-corp.demo',
    departmentId: 'DEP-ENG',
    departmentName: 'Engineering',
    domainId: 'DOM-CLD',
    domainName: 'Cloud & DevOps',
    designation: 'Infrastructure Engineer',
    status: 'ACTIVE',
    joiningDate: '2024-08-01',
    manager: 'Aakash Singhania',
    location: 'Pune Innovation Center',
    phone: '+91 98450 11031',
  },
  {
    employeeId: 'PRX-032',
    name: 'Zoya Qureshi',
    email: 'zoya.qureshi@prionix-corp.demo',
    departmentId: 'DEP-MKT',
    departmentName: 'Marketing',
    domainId: 'DOM-MKT',
    domainName: 'Growth & Marketing',
    designation: 'Event & Community Manager',
    status: 'ACTIVE',
    joiningDate: '2024-09-01',
    manager: 'Pooja Nair',
    location: 'Delhi Regional Office',
    phone: '+91 98450 11032',
  },
];

export const PROJECTS_DATA: ProjectItem[] = [
  {
    id: 'PRJ-101',
    name: 'Enterprise Agentic Mesh',
    description: 'Autonomous multi-agent orchestration for enterprise business workflows and cross-department telemetry.',
    team: 'AI Core & Platform Ops',
    domainId: 'DOM-AI',
    domainName: 'AI & Data Science',
    ownerName: 'Devika Krishnan',
    ownerEmployeeId: 'PRX-002',
    status: 'ACTIVE',
    priority: 'CRITICAL',
    startDate: '2026-01-15',
    deadline: '2026-11-30',
    completionPercentage: 68,
    budget: '₹4,50,00,000',
  },
  {
    id: 'PRJ-102',
    name: 'Zero-Trust Identity Fabric',
    description: 'Cryptographic policy enforcement, dynamic context-aware token rotation, and single-pane SSO access.',
    team: 'InfoSec & Core Arch',
    domainId: 'DOM-SEC',
    domainName: 'Cyber Security',
    ownerName: 'Chetan Bansal',
    ownerEmployeeId: 'PRX-013',
    status: 'ACTIVE',
    priority: 'HIGH',
    startDate: '2026-02-01',
    deadline: '2026-10-15',
    completionPercentage: 82,
    budget: '₹2,80,00,000',
  },
  {
    id: 'PRJ-103',
    name: 'Global Cloud Multi-Region Cluster',
    description: 'Zero-downtime distributed failover across Asia-South and Europe-West Kubernetes nodes.',
    team: 'Cloud DevOps',
    domainId: 'DOM-CLD',
    domainName: 'Cloud & DevOps',
    ownerName: 'Aakash Singhania',
    ownerEmployeeId: 'PRX-011',
    status: 'COMPLETED',
    priority: 'HIGH',
    startDate: '2025-06-01',
    deadline: '2026-05-15',
    completionPercentage: 100,
    budget: '₹3,20,00,000',
  },
  {
    id: 'PRJ-104',
    name: 'Editorial Design Token System v3',
    description: 'Unified accessible components, WCAG AAA compliance, and multi-brand token integration.',
    team: 'Design Systems & UI',
    domainId: 'DOM-UX',
    domainName: 'UI/UX Design',
    ownerName: 'Arjun Mehta',
    ownerEmployeeId: 'PRX-006',
    status: 'ACTIVE',
    priority: 'MEDIUM',
    startDate: '2026-03-01',
    deadline: '2026-12-01',
    completionPercentage: 54,
    budget: '₹1,10,00,000',
  },
  {
    id: 'PRJ-105',
    name: 'Autonomous QA Test Generation Matrix',
    description: 'Automated end-to-end synthetic scenario generator with regression prediction for enterprise deployments.',
    team: 'Quality Engineering',
    domainId: 'DOM-QA',
    domainName: 'Testing & QA',
    ownerName: 'Deepika Joshi',
    ownerEmployeeId: 'PRX-014',
    status: 'ACTIVE',
    priority: 'HIGH',
    startDate: '2026-04-01',
    deadline: '2026-11-15',
    completionPercentage: 45,
    budget: '₹1,75,00,000',
  },
  {
    id: 'PRJ-106',
    name: 'Predictive Fiscal Planning Engine',
    description: 'Real-time variance modeling, runway sensitivity analysis, and automated board deck generation.',
    team: 'Financial Engineering',
    domainId: 'DOM-FIN',
    domainName: 'Finance & Accounts',
    ownerName: 'Karthik Raman',
    ownerEmployeeId: 'PRX-007',
    status: 'ACTIVE',
    priority: 'MEDIUM',
    startDate: '2026-03-15',
    deadline: '2026-12-20',
    completionPercentage: 60,
    budget: '₹1,40,00,000',
  },
  {
    id: 'PRJ-107',
    name: 'Employee Wellbeing & Skill Matrix',
    description: 'Internal skill mapping, 360-growth pathways, mentorship pairing, and continuous feedback.',
    team: 'People Operations',
    domainId: 'DOM-HR',
    domainName: 'HR Operations',
    ownerName: 'Ananya Sharma',
    ownerEmployeeId: 'PRX-005',
    status: 'COMPLETED',
    priority: 'LOW',
    startDate: '2025-09-01',
    deadline: '2026-03-31',
    completionPercentage: 100,
    budget: '₹60,00,000',
  },
  {
    id: 'PRJ-108',
    name: 'Next-Gen Enterprise Portal v2',
    description: 'High-speed edge routing, micro-frontend federation, and offline state synchronization.',
    team: 'Frontend Platform',
    domainId: 'DOM-SWE',
    domainName: 'Software Engineering',
    ownerName: 'Kunal Saxena',
    ownerEmployeeId: 'PRX-021',
    status: 'PENDING',
    priority: 'HIGH',
    startDate: '2026-10-01',
    deadline: '2027-04-30',
    completionPercentage: 0,
    budget: '₹2,10,00,000',
  },
  {
    id: 'PRJ-109',
    name: 'Customer Growth Intelligence Hub',
    description: 'Omnichannel attribution graph, customer lifetime value modeling, and event ingestion pipeline.',
    team: 'Growth Marketing & Data',
    domainId: 'DOM-MKT',
    domainName: 'Growth & Marketing',
    ownerName: 'Pooja Nair',
    ownerEmployeeId: 'PRX-010',
    status: 'ON_HOLD',
    priority: 'LOW',
    startDate: '2026-01-10',
    deadline: '2026-08-30',
    completionPercentage: 30,
    budget: '₹95,00,000',
  },
  {
    id: 'PRJ-110',
    name: 'Hardware Security Module Integration',
    description: 'Hardware root of trust key lifecycle management for banking partners and enterprise audits.',
    team: 'Cyber Security',
    domainId: 'DOM-SEC',
    domainName: 'Cyber Security',
    ownerName: 'Chetan Bansal',
    ownerEmployeeId: 'PRX-013',
    status: 'PENDING',
    priority: 'MEDIUM',
    startDate: '2026-11-01',
    deadline: '2027-06-30',
    completionPercentage: 0,
    budget: '₹1,50,00,000',
  },
];

export const RECOGNITIONS_DATA: RecognitionItem[] = [
  // Monthly
  {
    id: 'REC-M1',
    employeeId: 'PRX-002',
    employeeName: 'Devika Krishnan',
    period: 'MONTHLY',
    rank: 1,
    category: 'AI Innovation Award',
    achievement: 'Designed and deployed low-latency streaming agent architecture reducing inference roundtrip by 42%.',
    score: 98,
    year: 2026,
    timeframeLabel: 'August 2026',
    awardedAt: '2026-08-31',
    departmentName: 'AI Research',
    avatarUrl: 'https://images.unsplash.com/photo-1580489944761-15a19d654956?w=150&auto=format&fit=crop&q=80',
  },
  {
    id: 'REC-M2',
    employeeId: 'PRX-011',
    employeeName: 'Aakash Singhania',
    period: 'MONTHLY',
    rank: 2,
    category: 'Outstanding Delivery',
    achievement: 'Completed zero-downtime multi-region Kubernetes migration across 48 services ahead of schedule.',
    score: 95,
    year: 2026,
    timeframeLabel: 'August 2026',
    awardedAt: '2026-08-31',
    departmentName: 'Engineering',
  },
  {
    id: 'REC-M3',
    employeeId: 'PRX-015',
    employeeName: 'Eshaan Nambiar',
    period: 'MONTHLY',
    rank: 3,
    category: 'Team Excellence',
    achievement: 'Delivered WCAG AAA enterprise design token system adopted across all customer-facing surfaces.',
    score: 92,
    year: 2026,
    timeframeLabel: 'August 2026',
    awardedAt: '2026-08-31',
    departmentName: 'Design',
  },
  // Quarterly
  {
    id: 'REC-Q1',
    employeeId: 'PRX-013',
    employeeName: 'Chetan Bansal',
    period: 'QUARTERLY',
    rank: 1,
    category: 'Zero-Trust Pioneer',
    achievement: 'Engineered automated vulnerability remediation agent preventing compliance drift across 200+ repositories.',
    score: 99,
    year: 2026,
    timeframeLabel: 'Q2 2026',
    awardedAt: '2026-06-30',
    departmentName: 'Engineering',
  },
  {
    id: 'REC-Q2',
    employeeId: 'PRX-002',
    employeeName: 'Devika Krishnan',
    period: 'QUARTERLY',
    rank: 2,
    category: 'AI Innovation Award',
    achievement: 'Authored 3 patent disclosures on multi-modal contextual embedding compression.',
    score: 96,
    year: 2026,
    timeframeLabel: 'Q2 2026',
    awardedAt: '2026-06-30',
    departmentName: 'AI Research',
  },
  {
    id: 'REC-Q3',
    employeeId: 'PRX-021',
    employeeName: 'Kunal Saxena',
    period: 'QUARTERLY',
    rank: 3,
    category: 'Front-end Craftsmanship',
    achievement: 'Spearheaded sub-100ms first contentful paint overhaul across internal management systems.',
    score: 93,
    year: 2026,
    timeframeLabel: 'Q2 2026',
    awardedAt: '2026-06-30',
    departmentName: 'Engineering',
  },
  // Yearly
  {
    id: 'REC-Y1',
    employeeId: 'PRX-003',
    employeeName: 'Dr. Radhika Sen',
    period: 'YEARLY',
    rank: 1,
    category: 'Prionix Luminary of the Year',
    achievement: 'Built company flagship AI Research foundation and scaled talent density by 300%.',
    score: 100,
    year: 2025,
    timeframeLabel: 'Annual 2025',
    awardedAt: '2025-12-20',
    departmentName: 'AI Research',
  },
  {
    id: 'REC-Y2',
    employeeId: 'PRX-004',
    employeeName: 'Vikram Malhotra',
    period: 'YEARLY',
    rank: 2,
    category: 'Architectural Excellence',
    achievement: 'Established unified microservices framework delivering 99.995% uptime across fiscal 2025.',
    score: 97,
    year: 2025,
    timeframeLabel: 'Annual 2025',
    awardedAt: '2025-12-20',
    departmentName: 'Engineering',
  },
  {
    id: 'REC-Y3',
    employeeId: 'PRX-005',
    employeeName: 'Ananya Sharma',
    period: 'YEARLY',
    rank: 3,
    category: 'Culture & Leadership Award',
    achievement: 'Pioneered transparent compensation bands and hybrid wellness protocols.',
    score: 94,
    year: 2025,
    timeframeLabel: 'Annual 2025',
    awardedAt: '2025-12-20',
    departmentName: 'Human Resources',
  },
];

export const ANNOUNCEMENTS_DATA: AnnouncementItem[] = [
  {
    id: 'ANN-01',
    title: 'Prionix Q3 All-Hands & Technical Innovation Showcase',
    category: 'EVENTS',
    description: 'Join CEO Office and Department Leads for our quarterly retrospective, showcasing project milestones in AI, security, and global infrastructure.',
    publishedDate: '2026-09-10',
    authorName: 'Ananya Sharma',
    authorEmployeeId: 'PRX-005',
    status: 'PUBLISHED',
    priority: 'HIGH',
  },
  {
    id: 'ANN-02',
    title: 'Updated Policy: Annual Health & Wellness Checkup Benefit',
    category: 'HR',
    description: 'Prionix has expanded annual executive health screenings and ergonomic allowances for all active employees across all campuses.',
    publishedDate: '2026-09-05',
    authorName: 'Fatima Zaidi',
    authorEmployeeId: 'PRX-016',
    status: 'PUBLISHED',
    priority: 'MEDIUM',
  },
  {
    id: 'ANN-03',
    title: 'Cloud Security Protocol: Mandatory Hardware Token Verification',
    category: 'POLICY',
    description: 'As part of our Zero-Trust initiative, all production access will require FIDO2/WebAuthn key authentication starting October 1st.',
    publishedDate: '2026-08-28',
    authorName: 'Chetan Bansal',
    authorEmployeeId: 'PRX-013',
    status: 'PUBLISHED',
    priority: 'HIGH',
  },
  {
    id: 'ANN-04',
    title: 'Generative AI & Agentic Workflows Masterclass',
    category: 'TRAINING',
    description: 'AI Research team is hosting a 4-part hands-on workshop on low-latency tool calling and evaluation pipelines for all engineers.',
    publishedDate: '2026-08-20',
    authorName: 'Devika Krishnan',
    authorEmployeeId: 'PRX-002',
    status: 'PUBLISHED',
    priority: 'MEDIUM',
  },
  {
    id: 'ANN-05',
    title: 'Fiscal Year 2027 Strategic Planning & Budgeting Guidance',
    category: 'PROJECTS',
    description: 'Department heads and project owners must submit preliminary headcount and infrastructure forecasts before October 15th.',
    publishedDate: '2026-08-15',
    authorName: 'Karthik Raman',
    authorEmployeeId: 'PRX-007',
    status: 'PUBLISHED',
    priority: 'LOW',
  },
  {
    id: 'ANN-06',
    title: 'New Bangalore Innovation Hub Phase 2 Expansion Complete',
    category: 'GENERAL',
    description: 'Phase 2 expansion of the BLR campus is complete with state-of-the-art research pods, cafeteria, and rooftop collaborative garden.',
    publishedDate: '2026-08-01',
    authorName: 'Manish Verma',
    authorEmployeeId: 'PRX-009',
    status: 'PUBLISHED',
    priority: 'MEDIUM',
  },
  {
    id: 'ANN-07',
    title: 'Annual Hackathon 2026: Agentic AI for Enterprise Operations',
    category: 'EVENTS',
    description: 'Registrations are open for the 48-hour global Prionix Hackathon. Cross-functional teams are invited to build autonomous tool workflows.',
    publishedDate: '2026-07-25',
    authorName: 'Vikram Malhotra',
    authorEmployeeId: 'PRX-003',
    status: 'PUBLISHED',
    priority: 'HIGH',
  },
  {
    id: 'ANN-08',
    title: 'Corporate Travel & Remote Expense Policy Update',
    category: 'POLICY',
    description: 'Streamlined approval workflows in the finance portal for domestic conference travel, client visits, and home broadband reimbursements.',
    publishedDate: '2026-07-10',
    authorName: 'Karthik Raman',
    authorEmployeeId: 'PRX-007',
    status: 'PUBLISHED',
    priority: 'LOW',
  },
];

export const DEMO_SALARY_DATA: Record<string, SalaryRecord[]> = {
  'PRX-002': [
    {
      id: 'SAL-002-2024',
      employeeId: 'PRX-002',
      ownerUid: 'employee-uid-demo',
      year: 2024,
      annualSalary: 1850000,
      monthlySalary: 154166,
      currency: 'INR',
      hikePercentage: 14.5,
      previousSalary: 1615000,
      revisionDate: '2024-04-01',
      designation: 'AI Research Engineer II',
      remarks: 'Exceeded performance benchmarks in ML model throughput and research delivery.',
    },
    {
      id: 'SAL-002-2025',
      employeeId: 'PRX-002',
      ownerUid: 'employee-uid-demo',
      year: 2025,
      annualSalary: 2150000,
      monthlySalary: 179166,
      currency: 'INR',
      hikePercentage: 16.2,
      previousSalary: 1850000,
      revisionDate: '2025-04-01',
      designation: 'Senior AI Research Engineer',
      remarks: 'Promotion to Senior role for leading agentic pipeline research and team mentorship.',
    },
    {
      id: 'SAL-002-2026',
      employeeId: 'PRX-002',
      ownerUid: 'employee-uid-demo',
      year: 2026,
      annualSalary: 2480000,
      monthlySalary: 206666,
      currency: 'INR',
      hikePercentage: 15.3,
      previousSalary: 2150000,
      revisionDate: '2026-04-01',
      designation: 'Senior AI Research Engineer',
      remarks: 'Annual merit increase reflecting patent contributions and agentic mesh architecture.',
    },
  ],
  'PRX-001': [
    {
      id: 'SAL-001-2024',
      employeeId: 'PRX-001',
      ownerUid: 'admin-uid-demo',
      year: 2024,
      annualSalary: 3400000,
      monthlySalary: 283333,
      currency: 'INR',
      hikePercentage: 11.0,
      previousSalary: 3060000,
      revisionDate: '2024-04-01',
      designation: 'VP of Engineering',
      remarks: 'Engineering organization scaling leadership bonus.',
    },
    {
      id: 'SAL-001-2025',
      employeeId: 'PRX-001',
      ownerUid: 'admin-uid-demo',
      year: 2025,
      annualSalary: 3800000,
      monthlySalary: 316666,
      currency: 'INR',
      hikePercentage: 12.0,
      previousSalary: 3400000,
      revisionDate: '2025-04-01',
      designation: 'VP of Engineering',
      remarks: 'Executive compensation review and leadership retention grant.',
    },
    {
      id: 'SAL-001-2026',
      employeeId: 'PRX-001',
      ownerUid: 'admin-uid-demo',
      year: 2026,
      annualSalary: 4300000,
      monthlySalary: 358333,
      currency: 'INR',
      hikePercentage: 13.1,
      previousSalary: 3800000,
      revisionDate: '2026-04-01',
      designation: 'VP of Engineering',
      remarks: 'Annual merit adjustment and executive performance bonus.',
    },
  ],
  'PRX-003': [
    {
      id: 'SAL-003-2025',
      employeeId: 'PRX-003',
      ownerUid: 'vikram-uid',
      year: 2025,
      annualSalary: 3100000,
      monthlySalary: 258333,
      currency: 'INR',
      hikePercentage: 14.0,
      previousSalary: 2720000,
      revisionDate: '2025-04-01',
      designation: 'Director of Platform Engineering',
      remarks: 'Platform stability 99.99% uptime achievement.',
    },
    {
      id: 'SAL-003-2026',
      employeeId: 'PRX-003',
      ownerUid: 'vikram-uid',
      year: 2026,
      annualSalary: 3500000,
      monthlySalary: 291666,
      currency: 'INR',
      hikePercentage: 12.9,
      previousSalary: 3100000,
      revisionDate: '2026-04-01',
      designation: 'Director of Platform Engineering',
      remarks: 'Annual merit hike for distributed systems modernization.',
    },
  ],
  'PRX-004': [
    {
      id: 'SAL-004-2025',
      employeeId: 'PRX-004',
      ownerUid: 'radhika-uid',
      year: 2025,
      annualSalary: 3400000,
      monthlySalary: 283333,
      currency: 'INR',
      hikePercentage: 15.0,
      previousSalary: 2950000,
      revisionDate: '2025-04-01',
      designation: 'Head of AI Research',
      remarks: 'Model publication in top-tier conference and research breakthrough.',
    },
    {
      id: 'SAL-004-2026',
      employeeId: 'PRX-004',
      ownerUid: 'radhika-uid',
      year: 2026,
      annualSalary: 3900000,
      monthlySalary: 3250000,
      currency: 'INR',
      hikePercentage: 14.7,
      previousSalary: 3400000,
      revisionDate: '2026-04-01',
      designation: 'Head of AI Research',
      remarks: 'Annual executive review and research patent grant.',
    },
  ],
  'PRX-005': [
    {
      id: 'SAL-005-2025',
      employeeId: 'PRX-005',
      ownerUid: 'ananya-uid',
      year: 2025,
      annualSalary: 2600000,
      monthlySalary: 216666,
      currency: 'INR',
      hikePercentage: 12.5,
      previousSalary: 2320000,
      revisionDate: '2025-04-01',
      designation: 'Director of People & Culture',
      remarks: 'Employer branding and high retention achievements.',
    },
    {
      id: 'SAL-005-2026',
      employeeId: 'PRX-005',
      ownerUid: 'ananya-uid',
      year: 2026,
      annualSalary: 2950000,
      monthlySalary: 245833,
      currency: 'INR',
      hikePercentage: 13.5,
      previousSalary: 2600000,
      revisionDate: '2026-04-01',
      designation: 'Director of People & Culture',
      remarks: 'Merit hike and talent program execution.',
    },
  ],
};

export const DEMO_MEDICAL_DATA: Record<string, MedicalRecord> = {
  'PRX-002': {
    employeeId: 'PRX-002',
    ownerUid: 'employee-uid-demo',
    bloodGroup: 'B+ (Positive)',
    emergencyContactName: 'Rajeev Krishnan',
    emergencyContactRelation: 'Spouse',
    emergencyPhone: '+91 98450 99881',
    allergies: ['Penicillin', 'Peanuts'],
    medicalNotes: 'Asthmatic in high-humidity seasons; inhaler prescribed for emergency use.',
    chronicConditions: ['Mild Asthma'],
    insurancePolicyNumber: 'PRX-STAR-CORP-98442-A',
    lastUpdated: '2026-08-15',
  },
  'PRX-001': {
    employeeId: 'PRX-001',
    ownerUid: 'admin-uid-demo',
    bloodGroup: 'O+ (Positive)',
    emergencyContactName: 'Meera Rao',
    emergencyContactRelation: 'Spouse',
    emergencyPhone: '+91 98450 77123',
    allergies: ['Shellfish'],
    medicalNotes: 'No chronic conditions reported. Annual executive physical cleared.',
    chronicConditions: [],
    insurancePolicyNumber: 'PRX-STAR-EXEC-11002-B',
    lastUpdated: '2026-07-20',
  },
};

export const DEMO_LEAVES_DATA: LeaveRecord[] = [
  {
    id: 'LV-201',
    employeeId: 'PRX-002',
    ownerUid: 'employee-uid-demo',
    employeeName: 'Devika Krishnan',
    leaveType: 'CASUAL',
    duration: 'FULL_DAY',
    startDate: '2026-09-18',
    endDate: '2026-09-19',
    daysCount: 2,
    reason: 'Family wedding and travel to home town.',
    status: 'PENDING',
    appliedAt: '2026-09-11 10:30 AM',
  },
  {
    id: 'LV-202',
    employeeId: 'PRX-002',
    ownerUid: 'employee-uid-demo',
    employeeName: 'Devika Krishnan',
    leaveType: 'SICK',
    duration: 'FULL_DAY',
    startDate: '2026-08-12',
    endDate: '2026-08-13',
    daysCount: 2,
    reason: 'Severe seasonal viral fever and physician-prescribed rest.',
    status: 'APPROVED',
    appliedAt: '2026-08-11 08:45 AM',
    reviewedBy: 'Dr. Radhika Sen',
    reviewedAt: '2026-08-11 09:30 AM',
  },
  {
    id: 'LV-203',
    employeeId: 'PRX-002',
    ownerUid: 'employee-uid-demo',
    employeeName: 'Devika Krishnan',
    leaveType: 'EARNED',
    duration: 'HALF_DAY',
    startDate: '2026-07-24',
    endDate: '2026-07-24',
    daysCount: 0.5,
    reason: 'Personal administration and municipal property documentation.',
    status: 'APPROVED',
    appliedAt: '2026-07-22 04:15 PM',
    reviewedBy: 'Dr. Radhika Sen',
    reviewedAt: '2026-07-23 10:00 AM',
  },
  {
    id: 'LV-204',
    employeeId: 'PRX-011',
    ownerUid: 'aakash-uid',
    employeeName: 'Aakash Singhania',
    leaveType: 'CASUAL',
    duration: 'FULL_DAY',
    startDate: '2026-09-22',
    endDate: '2026-09-24',
    daysCount: 3,
    reason: 'Annual hiking expedition with family.',
    status: 'PENDING',
    appliedAt: '2026-09-10 11:20 AM',
  },
  {
    id: 'LV-205',
    employeeId: 'PRX-015',
    ownerUid: 'eshaan-uid',
    employeeName: 'Eshaan Nambiar',
    leaveType: 'CASUAL',
    duration: 'HALF_DAY',
    startDate: '2026-09-15',
    endDate: '2026-09-15',
    daysCount: 0.5,
    reason: 'Dental appointment and checkup.',
    status: 'APPROVED',
    appliedAt: '2026-09-08 02:00 PM',
    reviewedBy: 'Arjun Mehta',
    reviewedAt: '2026-09-09 09:15 AM',
  },
  {
    id: 'LV-206',
    employeeId: 'PRX-001',
    ownerUid: 'admin-uid-demo',
    employeeName: 'Siddharth Rao',
    leaveType: 'EARNED',
    duration: 'FULL_DAY',
    startDate: '2026-08-21',
    endDate: '2026-08-22',
    daysCount: 2,
    reason: 'Speaking engagement at APAC Engineering Leadership Forum.',
    status: 'APPROVED',
    appliedAt: '2026-08-10 09:15 AM',
    reviewedBy: 'CEO Office',
    reviewedAt: '2026-08-11 11:00 AM',
  },
  {
    id: 'LV-207',
    employeeId: 'PRX-003',
    ownerUid: 'vikram-uid',
    employeeName: 'Vikram Malhotra',
    leaveType: 'CASUAL',
    duration: 'FULL_DAY',
    startDate: '2026-09-28',
    endDate: '2026-09-29',
    daysCount: 2,
    reason: 'Family anniversary celebrations.',
    status: 'PENDING',
    appliedAt: '2026-09-12 03:45 PM',
  },
  {
    id: 'LV-208',
    employeeId: 'PRX-007',
    ownerUid: 'karthik-uid',
    employeeName: 'Karthik Raman',
    leaveType: 'SICK',
    duration: 'FULL_DAY',
    startDate: '2026-07-15',
    endDate: '2026-07-16',
    daysCount: 2,
    reason: 'Severe food poisoning and physician-mandated recuperation.',
    status: 'APPROVED',
    appliedAt: '2026-07-15 07:30 AM',
    reviewedBy: 'CEO Office',
    reviewedAt: '2026-07-15 08:30 AM',
  },
  {
    id: 'LV-209',
    employeeId: 'PRX-013',
    ownerUid: 'chetan-uid',
    employeeName: 'Chetan Bansal',
    leaveType: 'CASUAL',
    duration: 'HALF_DAY',
    startDate: '2026-08-04',
    endDate: '2026-08-04',
    daysCount: 0.5,
    reason: 'Parent-teacher meeting at school.',
    status: 'APPROVED',
    appliedAt: '2026-08-02 01:15 PM',
    reviewedBy: 'Vikram Malhotra',
    reviewedAt: '2026-08-03 10:00 AM',
  },
  {
    id: 'LV-210',
    employeeId: 'PRX-021',
    ownerUid: 'meera-uid',
    employeeName: 'Meera Chawla',
    leaveType: 'EARNED',
    duration: 'FULL_DAY',
    startDate: '2026-09-02',
    endDate: '2026-09-04',
    daysCount: 3,
    reason: 'Personal vacation and wellness retreat.',
    status: 'APPROVED',
    appliedAt: '2026-08-20 11:30 AM',
    reviewedBy: 'Ananya Sharma',
    reviewedAt: '2026-08-22 04:00 PM',
  },
  {
    id: 'LV-211',
    employeeId: 'PRX-002',
    ownerUid: 'employee-uid-demo',
    employeeName: 'Devika Krishnan',
    leaveType: 'CASUAL',
    duration: 'FULL_DAY',
    startDate: '2026-06-10',
    endDate: '2026-06-11',
    daysCount: 2,
    reason: 'Weekend extension trip.',
    status: 'APPROVED',
    appliedAt: '2026-06-01 10:00 AM',
    reviewedBy: 'Dr. Radhika Sen',
    reviewedAt: '2026-06-02 09:30 AM',
  },
  {
    id: 'LV-212',
    employeeId: 'PRX-005',
    ownerUid: 'ananya-uid',
    employeeName: 'Ananya Sharma',
    leaveType: 'CASUAL',
    duration: 'HALF_DAY',
    startDate: '2026-08-18',
    endDate: '2026-08-18',
    daysCount: 0.5,
    reason: 'Home renovation inspection.',
    status: 'APPROVED',
    appliedAt: '2026-08-16 02:30 PM',
    reviewedBy: 'CEO Office',
    reviewedAt: '2026-08-17 11:00 AM',
  },
];

export const NOTIFICATIONS_DATA: NotificationItem[] = [
  {
    id: 'NOTIF-01',
    recipientUid: 'employee-uid-demo',
    employeeId: 'PRX-002',
    title: 'Leave Request Received',
    message: 'Your leave request for Sep 18-19 (Casual Leave) has been submitted for review by Dr. Radhika Sen.',
    type: 'LEAVE_STATUS',
    isRead: false,
    createdAt: '2026-09-11T10:30:00Z',
    link: '/leave',
  },
  {
    id: 'NOTIF-02',
    recipientUid: 'employee-uid-demo',
    employeeId: 'PRX-002',
    title: 'Award Recognition: AI Innovation Champion',
    message: 'Congratulations! You have been awarded Rank 1 in the Monthly Recognition Awards for Agentic Mesh Architecture.',
    type: 'RECOGNITION',
    isRead: false,
    createdAt: '2026-09-02T14:15:00Z',
    link: '/recognition',
  },
  {
    id: 'NOTIF-03',
    recipientUid: 'employee-uid-demo',
    employeeId: 'PRX-002',
    title: 'Company Announcement: Q3 All-Hands Meeting',
    message: 'Join CEO Office & Leads on Sep 18th for the Quarterly Retrospective and Innovation Demos.',
    type: 'ANNOUNCEMENT',
    isRead: true,
    createdAt: '2026-09-10T09:00:00Z',
    link: '/announcements',
  },
  {
    id: 'NOTIF-04',
    recipientUid: 'employee-uid-demo',
    employeeId: 'PRX-002',
    title: 'Project Milestone Reached',
    message: 'Project "Autonomous Agent Evaluation Mesh" has reached 88% completion ahead of the Oct 15 deadline.',
    type: 'PROJECT_ASSIGNMENT',
    isRead: true,
    createdAt: '2026-09-08T16:45:00Z',
    link: '/projects',
  },
  {
    id: 'NOTIF-05',
    recipientUid: 'employee-uid-demo',
    employeeId: 'PRX-002',
    title: 'Health & Wellness Benefit Credited',
    message: 'Your annual ergonomic stipend of 3,500 points has been credited to your Perks account.',
    type: 'COMPANY_UPDATE',
    isRead: false,
    createdAt: '2026-09-05T11:00:00Z',
    link: '/marketplace',
  },
  {
    id: 'NOTIF-06',
    recipientUid: 'admin-uid-demo',
    employeeId: 'PRX-001',
    title: 'Pending Leave Approvals',
    message: 'There are 3 pending leave applications requiring department review.',
    type: 'LEAVE_STATUS',
    isRead: false,
    createdAt: '2026-09-12T08:00:00Z',
    link: '/leave',
  },
  {
    id: 'NOTIF-07',
    recipientUid: 'admin-uid-demo',
    employeeId: 'PRX-001',
    title: 'Zero-Trust Hardware Token Audit',
    message: '84% of engineering staff have configured hardware tokens ahead of the Oct 1 deadline.',
    type: 'COMPANY_UPDATE',
    isRead: false,
    createdAt: '2026-09-11T15:20:00Z',
    link: '/security-audit',
  },
  {
    id: 'NOTIF-08',
    recipientUid: 'admin-uid-demo',
    employeeId: 'PRX-001',
    title: 'New Project Proposal Created',
    message: 'Vikram Malhotra submitted the Q4 Infrastructure Migration initiative for sign-off.',
    type: 'PROJECT_ASSIGNMENT',
    isRead: true,
    createdAt: '2026-09-09T17:10:00Z',
    link: '/projects',
  },
  {
    id: 'NOTIF-09',
    recipientUid: 'employee-uid-demo',
    employeeId: 'PRX-002',
    title: 'Perks Order Shipped: Logitech MX Master 3S',
    message: 'Your order PRX-ORD-9024 has shipped via BlueDart. Tracking: BDT-9028472.',
    type: 'COMPANY_UPDATE',
    isRead: true,
    createdAt: '2026-09-04T12:00:00Z',
    link: '/marketplace',
  },
  {
    id: 'NOTIF-10',
    recipientUid: 'employee-uid-demo',
    employeeId: 'PRX-002',
    title: 'Mentorship 1-on-1 Confirmed',
    message: 'Your session with Dr. Radhika Sen is confirmed for Sep 18, 10:00 AM at Innovation Pod 2.',
    type: 'COMPANY_UPDATE',
    isRead: true,
    createdAt: '2026-09-03T10:30:00Z',
    link: '/appointments',
  },
  {
    id: 'NOTIF-11',
    recipientUid: 'employee-uid-demo',
    employeeId: 'PRX-002',
    title: 'Security Compliance Reminder',
    message: 'Please verify your registered 2FA phone number in Employee Profile settings.',
    type: 'PROFILE_UPDATE',
    isRead: true,
    createdAt: '2026-08-28T09:00:00Z',
    link: '/profile',
  },
  {
    id: 'NOTIF-12',
    recipientUid: 'employee-uid-demo',
    employeeId: 'PRX-002',
    title: 'Training Registration Open',
    message: 'Registrations are now open for the "Low Latency Tool Calling" lab scheduled for Sep 25.',
    type: 'ANNOUNCEMENT',
    isRead: true,
    createdAt: '2026-08-21T14:00:00Z',
    link: '/announcements',
  },
  {
    id: 'NOTIF-13',
    recipientUid: 'employee-uid-demo',
    employeeId: 'PRX-002',
    title: 'Salary Slip August 2026 Published',
    message: 'Your confidential salary statement for August 2026 is now available for download.',
    type: 'COMPANY_UPDATE',
    isRead: true,
    createdAt: '2026-08-31T18:00:00Z',
    link: '/profile',
  },
  {
    id: 'NOTIF-14',
    recipientUid: 'admin-uid-demo',
    employeeId: 'PRX-001',
    title: 'Quarterly Headcount Forecast Due',
    message: 'Finance department has requested updated hiring quotas for Q4.',
    type: 'COMPANY_UPDATE',
    isRead: false,
    createdAt: '2026-09-12T11:00:00Z',
    link: '/analytics/workforce',
  },
  {
    id: 'NOTIF-15',
    recipientUid: 'employee-uid-demo',
    employeeId: 'PRX-002',
    title: 'Profile Contact Info Verified',
    message: 'Your emergency contact details were successfully synchronized with the central HRMS.',
    type: 'PROFILE_UPDATE',
    isRead: true,
    createdAt: '2026-08-16T15:30:00Z',
    link: '/profile',
  },
];

// Exactly 20 realistic enterprise marketplace products
export const MARKETPLACE_PRODUCTS_DATA: MarketplaceProduct[] = [
  {
    id: 'PROD-001',
    name: 'Herman Miller Aeron Ergonomic Chair',
    category: 'ERGONOMICS',
    description: 'Gold standard ergonomic task chair with posture-fit spinal support, 8Z pellicle mesh, and fully adjustable arms.',
    pricePoints: 6500,
    priceINR: 115000,
    imageUrl: 'https://images.unsplash.com/photo-1580481077195-c3a82da45899?w=600&auto=format&fit=crop&q=80',
    rating: 4.9,
    inStock: true,
    stockCount: 12,
    vendor: 'Herman Miller Official Partner',
    tags: ['Ergonomics', 'Posture', 'Executive', 'WFH'],
  },
  {
    id: 'PROD-002',
    name: 'Dell UltraSharp 34" Curved USB-C Hub Monitor (U3423WE)',
    category: 'HARDWARE',
    description: 'WQHD IPS Black panel with 2000:1 contrast ratio, 90W power delivery, built-in KVM switch, and RJ45 ethernet hub.',
    pricePoints: 4800,
    priceINR: 82000,
    imageUrl: 'https://images.unsplash.com/photo-1527443224154-c4a3942d3acf?w=600&auto=format&fit=crop&q=80',
    rating: 4.8,
    inStock: true,
    stockCount: 18,
    vendor: 'Dell Enterprise Solutions',
    tags: ['Monitor', 'Curved', 'Display', 'USB-C'],
  },
  {
    id: 'PROD-003',
    name: 'Sony WH-1000XM5 Wireless Noise-Canceling Headphones',
    category: 'AUDIO',
    description: 'Industry-leading noise cancellation with 8 microphones, Auto NC Optimizer, 30-hour battery life, and crystal-clear voice calls.',
    pricePoints: 2400,
    priceINR: 29990,
    imageUrl: 'https://images.unsplash.com/photo-1505740420928-5e560c06d30e?w=600&auto=format&fit=crop&q=80',
    rating: 4.9,
    inStock: true,
    stockCount: 25,
    vendor: 'Sony India Retail',
    tags: ['Audio', 'ANC', 'Wireless', 'Deep Focus'],
  },
  {
    id: 'PROD-004',
    name: 'Logitech MX Master 3S Wireless Performance Mouse',
    category: 'PRODUCTIVITY',
    description: 'Quiet Click technology, 8K DPI tracking on glass, MagSpeed electromagnetic scrolling, and multi-computer FLOW switching.',
    pricePoints: 950,
    priceINR: 10995,
    imageUrl: 'https://images.unsplash.com/photo-1615663245857-ac93bb7c39e7?w=600&auto=format&fit=crop&q=80',
    rating: 4.9,
    inStock: true,
    stockCount: 42,
    vendor: 'Logitech Commercial',
    tags: ['Mouse', 'Productivity', 'Bluetooth'],
  },
  {
    id: 'PROD-005',
    name: 'Keychron Q1 Pro Wireless Custom Mechanical Keyboard',
    category: 'PRODUCTIVITY',
    description: '75% layout, full aluminum CNC body, hot-swappable tactile switches, double-gasket mount, and QMK/VIA programmable firmware.',
    pricePoints: 1600,
    priceINR: 18999,
    imageUrl: 'https://images.unsplash.com/photo-1587829741301-dc798b83add3?w=600&auto=format&fit=crop&q=80',
    rating: 4.8,
    inStock: true,
    stockCount: 15,
    vendor: 'Keychron Direct',
    tags: ['Keyboard', 'Mechanical', 'Tactile'],
  },
  {
    id: 'PROD-006',
    name: 'Apple AirPods Pro (2nd Generation, USB-C)',
    category: 'AUDIO',
    description: 'Up to 2x more Active Noise Cancellation, Adaptive Audio, Personalized Spatial Audio, and MagSafe charging case.',
    pricePoints: 2200,
    priceINR: 24900,
    imageUrl: 'https://images.unsplash.com/photo-1600294037681-c80b4cb5b434?w=600&auto=format&fit=crop&q=80',
    rating: 4.8,
    inStock: true,
    stockCount: 30,
    vendor: 'Apple Authorized Enterprise',
    tags: ['Audio', 'Apple', 'Earbuds', 'ANC'],
  },
  {
    id: 'PROD-007',
    name: 'ErgoMax Electric Dual-Motor Height Adjustable Desk',
    category: 'ERGONOMICS',
    description: 'Solid European walnut tabletop (150x75cm), quad-memory digital LED controller, anti-collision sensor, and 120kg weight capacity.',
    pricePoints: 3600,
    priceINR: 46000,
    imageUrl: 'https://images.unsplash.com/photo-1595515106969-1ce29566ff1c?w=600&auto=format&fit=crop&q=80',
    rating: 4.7,
    inStock: true,
    stockCount: 8,
    vendor: 'ErgoMax Furniture Lab',
    tags: ['Standing Desk', 'Ergonomics', 'WFH Setup'],
  },
  {
    id: 'PROD-008',
    name: 'BenQ ScreenBar Pro Automatic Monitor Light Bar',
    category: 'PRODUCTIVITY',
    description: 'Space-saving asymmetrical optical design with zero screen glare, auto-dimming ambient light sensor, and ultra-wide illumination.',
    pricePoints: 1100,
    priceINR: 13990,
    imageUrl: 'https://images.unsplash.com/photo-1517420704952-d9f39e95b43e?w=600&auto=format&fit=crop&q=80',
    rating: 4.9,
    inStock: true,
    stockCount: 22,
    vendor: 'BenQ Commercial',
    tags: ['Desk Lamp', 'Eye Care', 'Monitor Bar'],
  },
  {
    id: 'PROD-009',
    name: 'Oura Ring Gen3 Horizon Wellness Tracker',
    category: 'WELLNESS',
    description: 'Accurate sleep stage tracking, HRV, daytime stress metrics, and recovery readiness score in a titanium water-resistant band.',
    pricePoints: 2800,
    priceINR: 34999,
    imageUrl: 'https://images.unsplash.com/photo-1605100804763-247f67b3557e?w=600&auto=format&fit=crop&q=80',
    rating: 4.7,
    inStock: true,
    stockCount: 14,
    vendor: 'Oura Health Enterprise',
    tags: ['Sleep Tracker', 'Wellness', 'Titanium'],
  },
  {
    id: 'PROD-010',
    name: 'Calm & Headspace Premium Annual Corporate Membership',
    category: 'WELLNESS',
    description: '12-month unlimited subscription to guided meditations, focus soundscapes, sleep stories, and mindful breathing practices.',
    pricePoints: 450,
    priceINR: 4999,
    imageUrl: 'https://images.unsplash.com/photo-1545205597-3d9d02c29597?w=600&auto=format&fit=crop&q=80',
    rating: 4.8,
    inStock: true,
    stockCount: 999,
    vendor: 'Prionix Employee Wellness Office',
    tags: ['Mental Health', 'Meditation', 'Subscription'],
  },
  {
    id: 'PROD-011',
    name: 'Ember Temperature Control Smart Mug 2 (14 oz)',
    category: 'PRODUCTIVITY',
    description: 'Maintains your chosen drinking temperature (50°C - 62.5°C) for 80 minutes on a single charge or all day on the charging coaster.',
    pricePoints: 1350,
    priceINR: 16500,
    imageUrl: 'https://images.unsplash.com/photo-1514432324607-a09d9b4aefdd?w=600&auto=format&fit=crop&q=80',
    rating: 4.6,
    inStock: true,
    stockCount: 16,
    vendor: 'Ember Technologies',
    tags: ['Smart Mug', 'Coffee', 'Desk Lifestyle'],
  },
  {
    id: 'PROD-012',
    name: 'Anker Prime 27,650mAh Power Bank (250W Multi-Port)',
    category: 'HARDWARE',
    description: 'Powers two laptops simultaneously with 140W max single-port USB PD 3.1 output and real-time digital status screen.',
    pricePoints: 1400,
    priceINR: 17999,
    imageUrl: 'https://images.unsplash.com/photo-1583863788434-e58a36330cf0?w=600&auto=format&fit=crop&q=80',
    rating: 4.9,
    inStock: true,
    stockCount: 20,
    vendor: 'Anker Official',
    tags: ['Power Bank', 'Fast Charging', 'Travel Tech'],
  },
  {
    id: 'PROD-013',
    name: 'Theragun Mini 2.0 Percussive Massage Device',
    category: 'WELLNESS',
    description: 'Pocket-sized muscle relief with QuietForce technology, 3 ergonomic speeds, and Bluetooth integration for tailored therapies.',
    pricePoints: 1700,
    priceINR: 19999,
    imageUrl: 'https://images.unsplash.com/photo-1544367567-0f2fcb009e0b?w=600&auto=format&fit=crop&q=80',
    rating: 4.7,
    inStock: true,
    stockCount: 11,
    vendor: 'Therabody Wellness',
    tags: ['Recovery', 'Massage', 'Health'],
  },
  {
    id: 'PROD-014',
    name: 'Kindle Paperwhite Signature Edition (32GB, Wireless)',
    category: 'PRODUCTIVITY',
    description: '6.8" 300 ppi glare-free display, auto-adjusting warm front light, wireless charging, and weeks of battery life for learning.',
    pricePoints: 1550,
    priceINR: 17999,
    imageUrl: 'https://images.unsplash.com/photo-1592496431122-2349e0fbc666?w=600&auto=format&fit=crop&q=80',
    rating: 4.9,
    inStock: true,
    stockCount: 24,
    vendor: 'Amazon Enterprise',
    tags: ['E-Reader', 'Books', 'Learning'],
  },
  {
    id: 'PROD-015',
    name: 'Elgato Stream Deck MK.2 Workspace Controller',
    category: 'PRODUCTIVITY',
    description: '15 customizable LCD keys to control apps, run terminal commands, mute Zoom mics, and automate engineering workflows with one tap.',
    pricePoints: 1300,
    priceINR: 14990,
    imageUrl: 'https://images.unsplash.com/photo-1618384887929-16ec33fab9ef?w=600&auto=format&fit=crop&q=80',
    rating: 4.8,
    inStock: true,
    stockCount: 19,
    vendor: 'Corsair / Elgato',
    tags: ['Stream Deck', 'Macros', 'Automation'],
  },
  {
    id: 'PROD-016',
    name: 'Bose SoundLink Revolve+ II Bluetooth Speaker',
    category: 'AUDIO',
    description: 'True 360° omnidirectional sound, water and dust-resistant aluminum body (IP55), flexible handle, and 17-hour battery life.',
    pricePoints: 2100,
    priceINR: 26500,
    imageUrl: 'https://images.unsplash.com/photo-1545454675-3531b543be5d?w=600&auto=format&fit=crop&q=80',
    rating: 4.8,
    inStock: true,
    stockCount: 14,
    vendor: 'Bose India',
    tags: ['Speaker', 'Bluetooth', 'Acoustics'],
  },
  {
    id: 'PROD-017',
    name: 'CalDigit TS4 Thunderbolt 4 Enterprise Dock (18-in-1)',
    category: 'HARDWARE',
    description: 'Massive 98W laptop charging, dual 6K display support, 2.5GbE Ethernet, 8 USB ports, and SD 4.0 card reader.',
    pricePoints: 3400,
    priceINR: 41000,
    imageUrl: 'https://images.unsplash.com/photo-1544716278-ca5e3f4abd8c?w=600&auto=format&fit=crop&q=80',
    rating: 4.9,
    inStock: true,
    stockCount: 7,
    vendor: 'CalDigit Global',
    tags: ['Thunderbolt', 'Docking Station', 'Dual 4K'],
  },
  {
    id: 'PROD-018',
    name: 'Bellroy Classic Backpack Plus (24L, Charcoal Recycled Fabric)',
    category: 'WELLNESS',
    description: 'Dual-compartment daypack with padded 16" laptop sleeve, quick-access tech pockets, and contoured lumbar back panel.',
    pricePoints: 1450,
    priceINR: 16900,
    imageUrl: 'https://images.unsplash.com/photo-1553062407-98eeb64c6a62?w=600&auto=format&fit=crop&q=80',
    rating: 4.8,
    inStock: true,
    stockCount: 22,
    vendor: 'Bellroy Australia',
    tags: ['Backpack', 'Commute', 'Waterproof'],
  },
  {
    id: 'PROD-019',
    name: 'Fellow Stagg EKG Electric Pour-Over Kettle (Matte Black)',
    category: 'PRODUCTIVITY',
    description: 'Precision gooseneck spout for controlled flow, to-the-degree temperature control dial, and 60-minute hold mode.',
    pricePoints: 1500,
    priceINR: 18000,
    imageUrl: 'https://images.unsplash.com/photo-1517256064527-09c73fc73e38?w=600&auto=format&fit=crop&q=80',
    rating: 4.9,
    inStock: true,
    stockCount: 13,
    vendor: 'Fellow Design Lab',
    tags: ['Coffee', 'Kitchen', 'Design Craft'],
  },
  {
    id: 'PROD-020',
    name: 'Cult.fit & StepSetGo Annual All-Access Fitness Pass',
    category: 'WELLNESS',
    description: 'Unlimited access to Cult gym centres, swimming pools, yoga studios, badminton courts, and 1-on-1 nutritionist consultations.',
    pricePoints: 1800,
    priceINR: 21500,
    imageUrl: 'https://images.unsplash.com/photo-1534438327276-14e5300c3a48?w=600&auto=format&fit=crop&q=80',
    rating: 4.7,
    inStock: true,
    stockCount: 150,
    vendor: 'Cult.fit Corporate Health',
    tags: ['Gym', 'Fitness', 'Sports', 'Wellness'],
  },
];

// Exactly 15 realistic enterprise demo orders
export const DEMO_ORDERS_DATA: DemoOrder[] = [
  {
    id: 'ORD-801',
    orderNumber: 'PRX-ORD-9021',
    employeeId: 'PRX-002',
    employeeName: 'Devika Krishnan',
    productId: 'PROD-004',
    productName: 'Logitech MX Master 3S Wireless Performance Mouse',
    productCategory: 'PRODUCTIVITY',
    quantity: 1,
    totalPoints: 950,
    totalAmount: 10995,
    orderDate: '2026-08-25',
    status: 'DELIVERED',
    shippingAddress: 'Prionix Bangalore Campus, Tower B Desk 4-12, Outer Ring Rd, Bengaluru 560103',
    trackingNumber: 'BLR-EXP-902184',
  },
  {
    id: 'ORD-802',
    orderNumber: 'PRX-ORD-9022',
    employeeId: 'PRX-001',
    employeeName: 'Siddharth Rao',
    productId: 'PROD-002',
    productName: 'Dell UltraSharp 34" Curved USB-C Hub Monitor (U3423WE)',
    productCategory: 'HARDWARE',
    quantity: 1,
    totalPoints: 4800,
    totalAmount: 82000,
    orderDate: '2026-08-28',
    status: 'DELIVERED',
    shippingAddress: 'Prionix Executive Suites, Floor 7, Koramangala 4th Block, Bengaluru 560034',
    trackingNumber: 'DEL-PRX-110029',
  },
  {
    id: 'ORD-803',
    orderNumber: 'PRX-ORD-9023',
    employeeId: 'PRX-003',
    employeeName: 'Vikram Malhotra',
    productId: 'PROD-003',
    productName: 'Sony WH-1000XM5 Wireless Noise-Canceling Headphones',
    productCategory: 'AUDIO',
    quantity: 1,
    totalPoints: 2400,
    totalAmount: 29990,
    orderDate: '2026-09-01',
    status: 'DELIVERED',
    shippingAddress: 'Prionix Bangalore Campus, Engineering Pod 3, Bengaluru 560103',
    trackingNumber: 'BDT-7719208',
  },
  {
    id: 'ORD-804',
    orderNumber: 'PRX-ORD-9024',
    employeeId: 'PRX-002',
    employeeName: 'Devika Krishnan',
    productId: 'PROD-008',
    productName: 'BenQ ScreenBar Pro Automatic Monitor Light Bar',
    productCategory: 'PRODUCTIVITY',
    quantity: 1,
    totalPoints: 1100,
    totalAmount: 13990,
    orderDate: '2026-09-04',
    status: 'SHIPPED',
    shippingAddress: 'Prionix Bangalore Campus, AI Research Hub Pod 1, Bengaluru 560103',
    trackingNumber: 'BDT-9028472',
  },
  {
    id: 'ORD-805',
    orderNumber: 'PRX-ORD-9025',
    employeeId: 'PRX-004',
    employeeName: 'Dr. Radhika Sen',
    productId: 'PROD-009',
    productName: 'Oura Ring Gen3 Horizon Wellness Tracker',
    productCategory: 'WELLNESS',
    quantity: 1,
    totalPoints: 2800,
    totalAmount: 34999,
    orderDate: '2026-09-05',
    status: 'PROCESSING',
    shippingAddress: 'Prionix Research Lab, Ground Floor A-Wing, Bengaluru 560103',
    trackingNumber: 'TRK-PEND-0905',
  },
  {
    id: 'ORD-806',
    orderNumber: 'PRX-ORD-9026',
    employeeId: 'PRX-005',
    employeeName: 'Ananya Sharma',
    productId: 'PROD-010',
    productName: 'Calm & Headspace Premium Annual Corporate Membership',
    productCategory: 'WELLNESS',
    quantity: 1,
    totalPoints: 450,
    totalAmount: 4999,
    orderDate: '2026-09-06',
    status: 'DELIVERED',
    shippingAddress: 'Digital Voucher Activation via corporate email: ananya.sharma@prionix-corp.demo',
    trackingNumber: 'DIGITAL-VOUCHER-05',
  },
  {
    id: 'ORD-807',
    orderNumber: 'PRX-ORD-9027',
    employeeId: 'PRX-007',
    employeeName: 'Karthik Raman',
    productId: 'PROD-011',
    productName: 'Ember Temperature Control Smart Mug 2 (14 oz)',
    productCategory: 'PRODUCTIVITY',
    quantity: 1,
    totalPoints: 1350,
    totalAmount: 16500,
    orderDate: '2026-09-07',
    status: 'SHIPPED',
    shippingAddress: 'Prionix Finance Wing, Tower C 3rd Floor, Bengaluru 560103',
    trackingNumber: 'FEDEX-9921048',
  },
  {
    id: 'ORD-808',
    orderNumber: 'PRX-ORD-9028',
    employeeId: 'PRX-011',
    employeeName: 'Aakash Singhania',
    productId: 'PROD-005',
    productName: 'Keychron Q1 Pro Wireless Custom Mechanical Keyboard',
    productCategory: 'PRODUCTIVITY',
    quantity: 1,
    totalPoints: 1600,
    totalAmount: 18999,
    orderDate: '2026-09-08',
    status: 'DELIVERED',
    shippingAddress: 'Prionix Software Center, Desk E-22, Bengaluru 560103',
    trackingNumber: 'DELHIVERY-339102',
  },
  {
    id: 'ORD-809',
    orderNumber: 'PRX-ORD-9029',
    employeeId: 'PRX-013',
    employeeName: 'Chetan Bansal',
    productId: 'PROD-012',
    productName: 'Anker Prime 27,650mAh Power Bank (250W Multi-Port)',
    productCategory: 'HARDWARE',
    quantity: 1,
    totalPoints: 1400,
    totalAmount: 17999,
    orderDate: '2026-09-09',
    status: 'CONFIRMED',
    shippingAddress: 'Prionix DevOps & Infra Cluster, Bengaluru 560103',
    trackingNumber: 'IN-TRANSIT-PENDING',
  },
  {
    id: 'ORD-810',
    orderNumber: 'PRX-ORD-9030',
    employeeId: 'PRX-015',
    employeeName: 'Eshaan Nambiar',
    productId: 'PROD-014',
    productName: 'Kindle Paperwhite Signature Edition (32GB, Wireless)',
    productCategory: 'PRODUCTIVITY',
    quantity: 1,
    totalPoints: 1550,
    totalAmount: 17999,
    orderDate: '2026-09-10',
    status: 'PROCESSING',
    shippingAddress: 'Design Studio 4, Prionix Creative Hub, Bengaluru 560103',
    trackingNumber: 'AMZN-CORP-48821',
  },
  {
    id: 'ORD-811',
    orderNumber: 'PRX-ORD-9031',
    employeeId: 'PRX-021',
    employeeName: 'Meera Chawla',
    productId: 'PROD-020',
    productName: 'Cult.fit & StepSetGo Annual All-Access Fitness Pass',
    productCategory: 'WELLNESS',
    quantity: 1,
    totalPoints: 1800,
    totalAmount: 21500,
    orderDate: '2026-09-10',
    status: 'DELIVERED',
    shippingAddress: 'Digital Voucher: meera.chawla@prionix-corp.demo',
    trackingNumber: 'CULT-FIT-9031',
  },
  {
    id: 'ORD-812',
    orderNumber: 'PRX-ORD-9032',
    employeeId: 'PRX-002',
    employeeName: 'Devika Krishnan',
    productId: 'PROD-018',
    productName: 'Bellroy Classic Backpack Plus (24L, Charcoal Recycled Fabric)',
    productCategory: 'WELLNESS',
    quantity: 1,
    totalPoints: 1450,
    totalAmount: 16900,
    orderDate: '2026-09-11',
    status: 'PROCESSING',
    shippingAddress: 'Prionix Bangalore Campus, Tower B Desk 4-12, Outer Ring Rd, Bengaluru 560103',
    trackingNumber: 'PENDING-DISPATCH',
  },
  {
    id: 'ORD-813',
    orderNumber: 'PRX-ORD-9033',
    employeeId: 'PRX-006',
    employeeName: 'Kunal Verma',
    productId: 'PROD-015',
    productName: 'Elgato Stream Deck MK.2 Workspace Controller',
    productCategory: 'PRODUCTIVITY',
    quantity: 1,
    totalPoints: 1300,
    totalAmount: 14990,
    orderDate: '2026-09-11',
    status: 'CONFIRMED',
    shippingAddress: 'Prionix Product Lab, Floor 2, Bengaluru 560103',
    trackingNumber: 'PRE-DISPATCH-VERIFY',
  },
  {
    id: 'ORD-814',
    orderNumber: 'PRX-ORD-9034',
    employeeId: 'PRX-008',
    employeeName: 'Ritu Agarwal',
    productId: 'PROD-019',
    productName: 'Fellow Stagg EKG Electric Pour-Over Kettle (Matte Black)',
    productCategory: 'PRODUCTIVITY',
    quantity: 1,
    totalPoints: 1500,
    totalAmount: 18000,
    orderDate: '2026-09-12',
    status: 'CONFIRMED',
    shippingAddress: 'Prionix Operations Center, Facility Management Pod 1, Bengaluru 560103',
    trackingNumber: 'ORDER-PACKING-STAGE',
  },
  {
    id: 'ORD-815',
    orderNumber: 'PRX-ORD-9035',
    employeeId: 'PRX-010',
    employeeName: 'Sneha Kulkarni',
    productId: 'PROD-006',
    productName: 'Apple AirPods Pro (2nd Generation, USB-C)',
    productCategory: 'AUDIO',
    quantity: 1,
    totalPoints: 2200,
    totalAmount: 24900,
    orderDate: '2026-09-12',
    status: 'CONFIRMED',
    shippingAddress: 'Prionix Marketing Studio, Room M-04, Bengaluru 560103',
    trackingNumber: 'SHIPMENT-ALLOCATED',
  },
];

// Exactly 16 realistic enterprise appointment slots
export const APPOINTMENT_SLOTS_DATA: AppointmentSlot[] = [
  {
    id: 'APT-101',
    title: 'AI Research Mentorship & Tool Calling Architecture',
    type: 'MENTORSHIP',
    hostEmployeeId: 'PRX-004',
    hostName: 'Dr. Radhika Sen',
    hostRole: 'Head of AI Research',
    attendeeEmployeeId: 'PRX-002',
    attendeeName: 'Devika Krishnan',
    date: '2026-09-18',
    startTime: '10:00 AM',
    endTime: '10:45 AM',
    durationMinutes: 45,
    location: 'Innovation Pod 2 - AI Research Wing',
    status: 'BOOKED',
    notes: 'Discussion of fallback ladders and low-latency evaluation benchmarks for Q4 production release.',
  },
  {
    id: 'APT-102',
    title: 'Platform Scalability & Multi-Tenant Architecture Review',
    type: '1_ON_1',
    hostEmployeeId: 'PRX-003',
    hostName: 'Vikram Malhotra',
    hostRole: 'Director of Platform Engineering',
    attendeeEmployeeId: 'PRX-013',
    attendeeName: 'Chetan Bansal',
    date: '2026-09-18',
    startTime: '02:00 PM',
    endTime: '02:30 PM',
    durationMinutes: 30,
    location: 'Meeting Room C-302 (Virtual Bridge Active)',
    status: 'BOOKED',
    notes: 'Kubernetes cluster resource quotas and ingress load balancing review.',
  },
  {
    id: 'APT-103',
    title: 'HR Benefits, Medical Insurance & Ergonomic Stipend Connect',
    type: 'HR_CONNECT',
    hostEmployeeId: 'PRX-005',
    hostName: 'Ananya Sharma',
    hostRole: 'Director of People & Culture',
    date: '2026-09-19',
    startTime: '11:00 AM',
    endTime: '11:30 AM',
    durationMinutes: 30,
    location: 'HR Advisory Suite, Floor 3',
    status: 'AVAILABLE',
    notes: 'Open 1-on-1 office hour for any queries on health policy, paternity/maternity, or wellness credits.',
  },
  {
    id: 'APT-104',
    title: 'Quarterly OKR & Performance Alignment Check-in',
    type: 'PERFORMANCE_REVIEW',
    hostEmployeeId: 'PRX-001',
    hostName: 'Siddharth Rao',
    hostRole: 'VP of Engineering',
    attendeeEmployeeId: 'PRX-003',
    attendeeName: 'Vikram Malhotra',
    date: '2026-09-19',
    startTime: '03:30 PM',
    endTime: '04:15 PM',
    durationMinutes: 45,
    location: 'Executive Boardroom B',
    status: 'BOOKED',
    notes: 'Quarterly review of platform milestones and cross-department collaboration indices.',
  },
  {
    id: 'APT-105',
    title: 'Product Roadmap & User Research Synchronization',
    type: '1_ON_1',
    hostEmployeeId: 'PRX-006',
    hostName: 'Kunal Verma',
    hostRole: 'Director of Product',
    date: '2026-09-21',
    startTime: '10:30 AM',
    endTime: '11:15 AM',
    durationMinutes: 45,
    location: 'Product War Room 1',
    status: 'AVAILABLE',
    notes: 'Sprint review of customer feedback loops for the Employee 360 mobile app.',
  },
  {
    id: 'APT-106',
    title: 'Design System Typography & Accessible Contrast Clinic',
    type: 'MENTORSHIP',
    hostEmployeeId: 'PRX-012',
    hostName: 'Arjun Mehta',
    hostRole: 'Director of Design',
    date: '2026-09-21',
    startTime: '02:00 PM',
    endTime: '02:45 PM',
    durationMinutes: 45,
    location: 'Design Lab & Figma Collaboration Room',
    status: 'AVAILABLE',
    notes: 'Reviewing WCAG AAA contrast scales, typography step ratios, and nested border radius mathematics.',
  },
  {
    id: 'APT-107',
    title: 'Cybersecurity Threat Modeling & Zero-Trust Audit',
    type: '1_ON_1',
    hostEmployeeId: 'PRX-013',
    hostName: 'Chetan Bansal',
    hostRole: 'Staff Infrastructure & Security Engineer',
    date: '2026-09-22',
    startTime: '11:30 AM',
    endTime: '12:00 PM',
    durationMinutes: 30,
    location: 'Security Operations Center (SOC)',
    status: 'AVAILABLE',
    notes: 'Guidance on FIDO2 key onboarding and IAM service account privilege scoping.',
  },
  {
    id: 'APT-108',
    title: 'Finance Budgeting & R&D Cloud Compute Cost Consultation',
    type: 'HR_CONNECT',
    hostEmployeeId: 'PRX-007',
    hostName: 'Karthik Raman',
    hostRole: 'Head of Finance',
    date: '2026-09-22',
    startTime: '04:00 PM',
    endTime: '04:30 PM',
    durationMinutes: 30,
    location: 'Finance Suite Room 204',
    status: 'AVAILABLE',
    notes: 'Departmental budget queries and capital equipment approvals.',
  },
  {
    id: 'APT-109',
    title: 'Deep Learning Model Optimization & Inference Latency',
    type: 'MENTORSHIP',
    hostEmployeeId: 'PRX-004',
    hostName: 'Dr. Radhika Sen',
    hostRole: 'Head of AI Research',
    date: '2026-09-23',
    startTime: '09:30 AM',
    endTime: '10:15 AM',
    durationMinutes: 45,
    location: 'Innovation Pod 2 - AI Research Wing',
    status: 'AVAILABLE',
    notes: 'Quantization techniques, vLLM acceleration, and cache-hit telemetry.',
  },
  {
    id: 'APT-110',
    title: 'Engineering Career Growth & Promotion Pathways',
    type: 'MENTORSHIP',
    hostEmployeeId: 'PRX-001',
    hostName: 'Siddharth Rao',
    hostRole: 'VP of Engineering',
    attendeeEmployeeId: 'PRX-002',
    attendeeName: 'Devika Krishnan',
    date: '2026-09-23',
    startTime: '03:00 PM',
    endTime: '03:45 PM',
    durationMinutes: 45,
    location: 'Executive Boardroom B',
    status: 'BOOKED',
    notes: 'Staff engineer roadmap, technical patents, and cross-organization leadership goals.',
  },
  {
    id: 'APT-111',
    title: 'People Operations & Career Mobility Consultation',
    type: 'HR_CONNECT',
    hostEmployeeId: 'PRX-016',
    hostName: 'Fatima Zaidi',
    hostRole: 'Senior HR Business Partner',
    date: '2026-09-24',
    startTime: '10:00 AM',
    endTime: '10:30 AM',
    durationMinutes: 30,
    location: 'HR Meeting Room 1',
    status: 'AVAILABLE',
    notes: 'Internal job transfers, department rotations, and skill development stipends.',
  },
  {
    id: 'APT-112',
    title: 'Enterprise Architecture & Cloud Database Scalability',
    type: '1_ON_1',
    hostEmployeeId: 'PRX-003',
    hostName: 'Vikram Malhotra',
    hostRole: 'Director of Platform Engineering',
    date: '2026-09-24',
    startTime: '04:00 PM',
    endTime: '04:45 PM',
    durationMinutes: 45,
    location: 'Engineering Pod 3',
    status: 'AVAILABLE',
    notes: 'Firestore indexing strategies, transaction durability, and offline sync resilience.',
  },
  {
    id: 'APT-113',
    title: 'Quarterly Engineering Retrospective: AI Agent Infrastructure',
    type: 'PERFORMANCE_REVIEW',
    hostEmployeeId: 'PRX-004',
    hostName: 'Dr. Radhika Sen',
    hostRole: 'Head of AI Research',
    date: '2026-09-25',
    startTime: '11:00 AM',
    endTime: '11:45 AM',
    durationMinutes: 45,
    location: 'Innovation Pod 1',
    status: 'AVAILABLE',
    notes: 'Formal quarterly evaluation of AI research initiatives and research publications.',
  },
  {
    id: 'APT-114',
    title: 'Marketing & Brand Strategy Review for Developer Advocacy',
    type: '1_ON_1',
    hostEmployeeId: 'PRX-010',
    hostName: 'Sneha Kulkarni',
    hostRole: 'Head of Brand & Growth',
    date: '2026-09-25',
    startTime: '02:30 PM',
    endTime: '03:00 PM',
    durationMinutes: 30,
    location: 'Marketing Studio',
    status: 'AVAILABLE',
    notes: 'Technical blog series, open-source community outreach, and developer conference talks.',
  },
  {
    id: 'APT-115',
    title: 'Employee Wellness & Ergonomic Consultation (Physio)',
    type: 'HR_CONNECT',
    hostEmployeeId: 'PRX-005',
    hostName: 'Ananya Sharma',
    hostRole: 'Director of People & Culture',
    attendeeEmployeeId: 'PRX-015',
    attendeeName: 'Eshaan Nambiar',
    date: '2026-09-26',
    startTime: '10:30 AM',
    endTime: '11:00 AM',
    durationMinutes: 30,
    location: 'Campus Wellness Clinic',
    status: 'BOOKED',
    notes: 'Onsite physiotherapist posture consultation and desk setup prescription.',
  },
  {
    id: 'APT-116',
    title: 'DevOps CI/CD Pipeline Automation & Security Gates',
    type: 'MENTORSHIP',
    hostEmployeeId: 'PRX-013',
    hostName: 'Chetan Bansal',
    hostRole: 'Staff Infrastructure & Security Engineer',
    date: '2026-09-26',
    startTime: '03:00 PM',
    endTime: '03:45 PM',
    durationMinutes: 45,
    location: 'SOC Room 102',
    status: 'AVAILABLE',
    notes: 'GitHub Actions secret masking, container scanning, and canary deployment rollouts.',
  },
];

